@startuml

package "LDO" {
  [LM2940CT]
}

package "MCU" {
  [ESP32 I2S Pins] 
}

package "Codec" {
  [PCM5102] 
}

package "FilterStage" {
    package "Amp1 - Single Supply" {
    [MCP6001_1] 
  }

  [ES2 Lab Circuit] 

    package "Amp2 - Single Supply" {
    [MCP6001_2] 
  }
}

package "Power Amp Stage" {
  [TPA711] 
}

[LM2940CT] -right-> [ESP32 I2S Pins]: stable 5V
[ESP32 I2S Pins]  -right->   [Codec]: Bluetooth Signal Conversion 
[Codec]    -->         [FilterStage]: Signal Amplification
[MCP6001_1]     -->   [ES2 Lab Circuit]: Filtering 
[ES2 Lab Circuit]   -->   [MCP6001_2]: Signal Amplification
[MCP6001_2]     -right->   [TPA711]: Power Amplification with AUX/Speaker send
[Codec] --> [TPA711]: Unfiltered Signal 

@enduml
